services:
  _defaults:
    autoconfigure: true

  Mindbird\ContaoNodeOverlay\Controller\NodesOverlayContentElementController:
    autoconfigure: true
    arguments:
      $scopeMatcher: '@contao.routing.scope_matcher'
      $nodeManager: '@terminal42_node.manager'